import type { PolyculeData } from '../types.js';
// Generated by: npm run build:client
// If this import errors, run `npm run build:client` first.
import { CLIENT_BUNDLE } from '../generated/client-bundle.js';

export interface HtmlOptions {
  title?: string;
}

export function generateStandaloneHTML(data: PolyculeData, opts: HtmlOptions = {}): string {
  const title = opts.title ?? 'Polycule Map';
  const jsonData = JSON.stringify(data);
  const dark = data.settings.theme === 'dark';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>${escHtml(title)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html, body { width: 100%; height: 100%; overflow: hidden; }
    body { background: ${dark ? '#0d1117' : '#f0f4f8'}; }
    #polymap-root { width: 100vw; height: 100vh; }
  </style>
</head>
<body>
  <div id="polymap-root"></div>
  <script>window.__POLYMAP_DATA__ = ${jsonData};</script>
  <script>${CLIENT_BUNDLE}</script>
</body>
</html>`;
}

/**
 * Generates a self-contained embed script.
 * Usage: add <div id="polymap-root" style="width:100%;height:600px;"></div>
 *        then <script src="polycule-embed.js"></script>
 */
export function generateEmbedJS(data: PolyculeData): string {
  const jsonData = JSON.stringify(data);
  return `(function(){window.__POLYMAP_DATA__=${jsonData};${CLIENT_BUNDLE}})();`;
}

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
